# prettier-ignore
version: '3.7'

services:

  # Obortech web application
  obortech_app:
    container_name: obortech_app
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - 4000:4000
    depends_on:
      - obortech_mysqldb
    links:
      - obortech_mysqldb:obortech_mysqldb
    volumes:
      - ./:/app
    environment:
      CHOKIDAR_USEPOLLING: 'true'
      MYSQL_HOST_IP: obortech_mysqldb
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: react
    networks:
      - boilerplate-network

  # MySQL database for users and organizations
  obortech_mysqldb:
    image: mysql:8.0.28
    logging:
      driver: none
    container_name: obortech_mysqldb
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: react
    volumes:
      - ./data/db-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - boilerplate-network

  # PHPMyAdmin interface to manage MySQL database
  phpmyadmin:
    depends_on:
      - obortech_mysqldb
    image: phpmyadmin/phpmyadmin:5
    logging:
      driver: none
    container_name: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    links:
      - obortech_mysqldb:obortech_mysqldb
    environment:
      PMA_HOSTS: obortech_mysqldb
      UPLOAD_LIMIT: 300M
      PMA_PORT: 3306
      PMA_PMADB: react
    networks:
      - boilerplate-network

networks:
  boilerplate-network:
    driver: bridge
