export const adminURL = [
    '/project',
    '/event',
    '/document',
    '/iot',
    '/analytics',
    '/user-data-request',
    '/allevent',
    '/alldocument',
    '/allanalytics',
    '/user-agreement',
    '/station',
    '/group-3',
    '/group-2',
    '/group-1',
    '/item',
    '/category',
    '/device',
    '/languages',
    '/type-title',
    '/participant',
    '/workers',
    '/submission-request',
    '/privacy-policy',
    '/data-usage-policy',
    '/form-builder',
    '/invitations',
]
export const ceoURL = ['/event', '/document', '/iot', '/analytics', '/user-data-request', '/allevent', '/alldocument', '/allanalytics', '/user-agreement', '/participant', '/workers', '/submission-request', '/data-usage-policy', '/form-builder', '/smart-contracts']
export const managerURL = [
    '/project',
    '/event',
    '/document',
    '/iot',
    '/analytics',
    '/user-data-request',
    '/allevent',
    '/alldocument',
    '/allanalytics',
    '/user-agreement',
    '/inventory',
    '/station',
    '/nft-management',
    '/group-3',
    '/group-2',
    '/group-1',
    '/item',
    '/category',
    '/inventory-manager',
    '/participant',
    '/workers',
    '/submission-request',
    '/data-usage-policy',
    '/form-builder',
    'dropdown-item',
]
export const seniorManagerURL = ['/event', '/document', '/iot', '/analytics', '/user-data-request', '/allevent', '/alldocument', '/allanalytics', '/user-agreement', '/participant', '/workers', '/submission-request', '/data-usage-policy', '/form-builder', '/smart-contracts']
export const userURL = ['/event', '/document', '/iot', '/analytics', '/user-data-request', '/allevent', '/alldocument', '/allanalytics', '/user-agreement']
export const publicUserURL = ['/event', '/iot', '/analytics', '/track-item', '/allevent']
export const assetElementNames = ['TransferAsset', 'CreateAsset', 'RemoveAsset']
