export const INITIAL_PAGINATION_STATE = {
    list: [],
    pageNumber: 0,
    totalPages: 0,
    totalCount: 0,
}

export const LOADER_TYPES = {
    PROJECT_CATEGORIES: 'PROJECT_CATEGORIES',
    EVENT_CATEGORIES: 'EVENT_CATEGORIES',
    DOCUMENT_CATEGORIES: 'DOCUMENT_CATEGORIES',
    PARTICIPANT_CATEGORIES: 'PARTICIPANT_CATEGORIES',
    DOCUMENT_TYPES: 'DOCUMENT_TYPES',
    USER_TYPES: 'USER_TYPES',
    USER_TITLES: 'USER_TITLES',
    ORGANIZATIONS: 'ORGANIZATIONS',
    PROJECTS: 'PROJECTS',
    GROUPS: 'GROUPS',
    ADD: 'ADD',
    DELETE: 'DELETE',
    UPDATE: 'UPDATE',
    UPSERT: 'UPSERT',
    APPROVE: 'APPROVE',
    TRUCKS: 'TRUCKS',
    CONTAINERS: 'CONTAINERS',
    ITEMS: 'ITEMS',
    STATIONS: 'STATIONS',
    INVITATIONS: 'INVITATIONS',
    FETCHING: 'FETCHING',
    WORKERS: 'WORKERS',
}

export const DEVICE_PAGE_TAB = {
    DEVICE: 'DEVICE',
    VENDOR: 'VENDOR',
}

export const CATEGORY_PAGE_TAB = {
    PROJECT: 'PROJECT',
    EVENT: 'EVENT',
    DOCUMENT: 'DOCUMENT',
    PARTICIPANT: 'PARTICIPANT',
}

export const TYPE_TITLE_PAGE_TAB = {
    USER_TYPES: 'USER_TYPES',
    USER_TITLES: 'USER_TITLES',
    DOCUMENT_TYPES: 'DOCUMENT_TYPES',
}

export const LISTING_PAGE_TAB = {
    PROJECT_LISTING: 'PROJECT_LISTING',
    TEMPLATE_LISTING: 'TEMPLATE_LISTING',
    ARCHIVED_LISTING: 'ARCHIVED_LISTING',
}
export const SMART_CONTRACT_PAGE_TAB = {
    SMART_CONTRACT_LISTING: 'SMART_CONTRACT_LISTING',
    SMART_CONTRACT_DETAILS: 'SMART_CONTRACT_DETAILS',
    COMMENTS: 'COMMENTS',
    APPROVALS: 'APPROVALS',
    CODE_ACCESS: 'CODE_ACCESS',
}

export const INVENTORY_PAGE_TAB = {
    MY_ASSETS_CLASSES: 'MY_ASSETS_CLASSES',
    CATEGORIES: 'CATEGORIES',
    UNCATEGORIZED_ASSET_CLASSES: 'UNCATEGORIZED_ASSET_CLASSES',
}
